version : '2'
services:
 dropwizard:
   build: .
   image: drop-wz
   restart: always
   ports:
    - 8080
    - 8081
   logging:
     driver: journald

 proxy:
   image: haproxy:1.7
   restart: always
   volumes:
    - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
   links:
    - dropwizard
   ports:
    - 0.0.0.0:8082:8080
    - 127.0.0.1:8081:8081


